### PR TITLE
add method to producer

### PR DESCRIPTION
**Pull request by gregoryrinaldi**

### CODE REVIEW

**Review by stainii — CHANGES_REQUESTED** [review]
Does this new method work? What happens in the original getMessage method when you provide null as a class? It will try to cast to null? Sounds fishy?

EDIT: After a second look, I see that I got confused. I would expect that the argument "type" would be of type `Class<T>`, but it is `Class `(without generics). T is actually nowhere defined if you use the AbstractConsumer like consumer.getMessage().

If I type `TextMessage message = getConsumer().getMessage(jmsMessageID, TextMessage.class, 10000L);`, the code compiles.
If I type `String message = getConsumer().getMessage(jmsMessageID, TextMessage.class, 10000L);`, the code compiles. **This is very dangerous.**

May I suggest that, instead of making the type optional, we enforce the type by changing Class to `Class<T>`?
And if you want to have a method that defaults to returning TextMessage.class, define that it returns TextMessage instead of T?

**Review by ebrygg — CHANGES_REQUESTED** [review]
I'm with @stainii on this. But I must say that the inital method that just logs the type is kinda fubar to.
But let us not make it worse.

**Comment by gregoryrinaldi** [comment]
Guys this parameter is only used for logging! It doesn't break anything. This parameter makes it almost impossible to test.

**Comment by gregoryrinaldi** [comment]
Ok I can try the proposition go Stijn. But what is the use of this parameter?

**Comment by gregoryrinaldi** [comment]
Normally the implementing class should provide the type like in AbstractDAO for example I really don't see the point of this parameter it is useless at the moment and above al makes it difficult to unit test/mock/stub etc. I have tested it with rules and raises no issues.

**Comment by gregoryrinaldi** [comment]
test me

**Comment by stainii** [comment]
The problem does not lie in the removal of the parameter. The whole getMessage() method is defined dangerously. Any of these 3 lines compile:

```
TextMessage message = consumer.getMessage("sdfsd", TextMessage.class);
String message2 = consumer.getMessage("sdfsd", TextMessage.class);
MySuperSpecialClass message3 = consumer.getMessage("sdfsd", TextMessage.class);
```

This can be solved by replacing the parameter `Class type` with `Class<T> type`

**Comment by gregoryrinaldi** [comment]
Hi Stijn I agree the class needs a complete revision

**Pull request closed without merging**
